#!/bin/bash

# check argument
if [ -z "$1" ]; then
    # report right usage
    echo "usage: $0 <id>"
    exit
fi

# start conversion
./conv $1

# check the return value
if [ $? = 0 ]; then
    # conversion has successfuly completed
    echo "$0 : done!"
else
    # if we are here then some error occured
    echo "$0 : some error occured"
fi
